{"timestamp": "2024-03-04 21:58:56.388321", "exception": "user forced crash", "traceback": "Traceback (most recent call last):\n  File \"/home/adrian/Documents/GitHub/wdhs-alevel-flight-sim/OpenPyFlySim/flight_sim.py\", line 469, in main\n    raise Exception(\"user forced crash\")\nException: user forced crash\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/adrian/Documents/GitHub/wdhs-alevel-flight-sim/OpenPyFlySim/flight_sim.py\", line 504, in main\n    timeTaken, currTime, verticelist, colCheck])\nUnboundLocalError: local variable 'timeTaken' referenced before assignment\n", "variables": "[]", "usertext": "", "checksum": "2af3162264409332bac6fa6b2eab77ab", "systemDetails": "posix.uname_result(sysname='Linux', nodename='adrian', release='6.5.0-21-generic', version='#21~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Feb  9 13:32:52 UTC 2', machine='x86_64')", "logchecksum": "d35da4c70d2f672435608d591c98e667", "sent": 1}