{"timestamp": "2023-03-04 22:13:35.986421", "exception": "user forced crash", "traceback": "Traceback (most recent call last):\n  File \"/home/adrian/Documents/GitHub/wdhs-alevel-flight-sim/OpenPyFlySim/flight_sim.py\", line 469, in main\n    raise Exception(\"user forced crash\")\nException: user forced crash\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/adrian/Documents/GitHub/wdhs-alevel-flight-sim/OpenPyFlySim/flight_sim.py\", line 504, in main\n    timeTaken, currTime, verticelist, colCheck])\nUnboundLocalError: local variable 'timeTaken' referenced before assignment\n", "variables": "[]", "usertext": "", "checksum": "5b1cfa13eb8bd1b7ccdced1429ff9b87", "systemDetails": "posix.uname_result(sysname='Linux', nodename='adrian', release='6.5.0-21-generic', version='#21~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Feb  9 13:32:52 UTC 2', machine='checksum": "928baa944aabe7bbae389bb9cf681142", "sent": 0}